### PR TITLE
Leo/fix onboarding

### PR DESCRIPTION
**Pull request by lmangall**
Now the onboarding is triggered, all the redirections happen in app and not home (or both)
The UI of the onboarding has been enhanced

### CODE REVIEW

**Comment by Danielg1406** [comment]
I like the onboarding a lot, love the emoji animations. The only thing I noticed is that the next button skips completely the onboarding

**Comment by lmangall** [comment]
I changed it for a skip button

**Comment by Danielg1406** [comment]
Checking a little more the copy of each slide of the onboarding I would change the copy of the last slide. I think saying thanks for using our service sounds very formal and weird because we are not giving any service. I would change it to something like keep sharing with friends and family to earn more or something more to motivate them to share the app.

**Comment by Danielg1406** [comment]
ok, but I just noticed something in the home it's showing it two times. I don't know if it's a bug for testing locally but it's weird.

Screenshot 2024-07-07 at 10 00 59 PM

**Comment by lmangall** [comment]
@Danielg1406 The small tweaks are done, the double home is strange, I don't have it. Maybe try `git restore .` on the branch...

**Comment by Danielg1406** [comment]
what is a 4 turn? why did you put that in the quest? I think that is confusing, keep it simple like it was

**Comment by lmangall** [comment]
https://en.wikipedia.org/wiki/Turn-taking

**Review by Danielg1406 — APPROVED** [review]
I think the content in the quest is weird but it's more important to test on production if the onboarding works

**Pull request merged**
