### PR TITLE
feature App: add icons in nav bar

### PR DESCRIPTION
**Pull request by Danielg1406**
Add Icons in the nav bar to make it more visible. Currently, even with padding the navbar has a specific size based on the device. The icons would help to give it a minimum high of at least 30px, so it is easier for the user to see it and press on it

### CODE REVIEW

**Comment by lmangall** [comment]
Why is the icon for _home_ a house ?
I tried to batch import but apparently it's not possible.

**Comment by Danielg1406** [comment]
> Why is the icon for _home_ a house ?

What do you mean? it's currently a circle with a plus. I didn't manage to find a better one. I don't know why they only have a few to import but not all the ones that show in Figma. Maybe I'm missing something.
Screenshot 2024-07-15 at 9 57 53 PM
those are the only ones available

> I tried to batch import but apparently it's not possible.

Yeah, it's annoying.

**Comment by lmangall** [comment]
Sorry, I meant "why is it _not_ a house"

Don't you think it's really misleading this "+" ?
We can use react-icons, the package is already there, I used it for the top right login that we got rid of

https://react-icons.github.io/react-icons/

**Comment by Danielg1406** [comment]
> Sorry, I meant "why is it _not_ a house"
> 
> Don't you think it's really misleading this "+" ? We can use react-icons, the package is already there, I used it for the top right login that we got rid of
> 
> https://react-icons.github.io/react-icons/

done @lmangall

**Review by 552020 — APPROVED** [review]
LGTM!

**Pull request merged**
