### PR TITLE
Danielgomeza1406/cha 512 fix agreesale modal to work when closed

### PR DESCRIPTION
**Pull request by Danielg1406**
- [x] Replace the text area with a better and more functional option.
- [x] Fix the success modal to avoid showing "success" two times and add more information to it.
- [x] Convert the categories in my summary to accordions and display a message when they're empty with a small explanation.
- [x] Fix the AgreeSale modal to work again when closed.
- [x] Add functionality for the modals to close when tapping outside them.
- [x] Improve the UI of the modals.
- [x] Have a lighter background for the modals when in light mode.
- [x] Locked the buttons in my chats and my invitations if there are no chats selected.
- [ ] Keep the phone number in the input even when the user switches between chips.

### CODE REVIEW

**Comment by lmangall** [comment]
@552020 Could you review this PR ? I already discussed  some details with @Danielg1406  so it would be better if you give your opinion on the UI side, also if you have suggestions for the content of the empty categories in My Summary

**Review by 552020 — CHANGES_REQUESTED** [review]
1. I see a black background behind the modal

image

2. When I open 1 drop down element everyone opens and not the single one

image

image

3. I know that there are tho standards for the direction of the chevron: I studied the problem some time ago. I like more the other standard: horizonal (closed), down (open). But it's just a matter or taste. You don't have to change it. 

4. The emty invitations element could have a line about what we will show there. 

5. When I tried to sell new chats (after Login) starting as Invitee I got stucked on the sell button. I couldn't continue from there. I tried two times same result

image

Otherwise perfect!

**Comment by Danielg1406** [comment]
> 1. I see a black background behind the modal

This is meant to be that way to cover the content that is behind. I can maybe look for a lighter tone for the light mode.

> 2. When I open 1 drop down element everyone opens and not the single one

I'll try to change it 👌

> 3. I know that there are tho standards for the direction of the chevron: I studied the problem some time ago. I like more the other standard: horizonal (closed), down (open). But it's just a matter or taste. You don't have to change it.

yeah, unfortunately the UI component comes by default with those two states. I would need to use a different component.

> 4. The emty invitations element could have a line about what we will show there.

I don't understand which elements you're talking about. Could you clarify what you mean, please?

> 5. When I tried to sell new chats (after Login) starting as Invitee I got stucked on the sell button. I couldn't continue from there. I tried two times same result

As far as I see, you don't have any chats selected. Could you maybe record a video of the whole interaction so I have more context about where the problem comes.

**Comment by 552020** [comment]
> 1. I see a black background behind the modal
> 
> image
> 2. When I open 1 drop down element everyone opens and not the single one
> 
> image image
> 3. I know that there are tho standards for the direction of the chevron: I studied the problem some time ago. I like more the other standard: horizonal (closed), down (open). But it's just a matter or taste. You don't have to change it.
> 4. The emty invitations element could have a line about what we will show there.
> 5. When I tried to sell new chats (after Login) starting as Invitee I got stucked on the sell button. I couldn't continue from there. I tried two times same result
> 
> image
> Otherwise perfect!



> > 1. I see a black background behind the modal
> 
> This is meant to be that way to cover the content that is behind. I can maybe look for a lighter tone for the light mode.
> 

What about white with no transparency or a super light grey?

> > 2. When I open 1 drop down element everyone opens and not the single one
> 
> I'll try to change it 👌
> 

But it's not so critical. 

> > 3. I know that there are tho standards for the direction of the chevron: I studied the problem some time ago. I like more the other standard: horizonal (closed), down (open). But it's just a matter or taste. You don't have to change it.
> 
> yeah, unfortunately the UI component comes by default with those two states. I would need to use a different component.
> 
then it's good like this

> > 4. The emty invitations element could have a line about what we will show there.
> 
> I don't understand which elements you're talking about. Could you clarify what you mean, please?
> 

My Invitations, when it is empty. The category. It's just blank. 

> > 5. When I tried to sell new chats (after Login) starting as Invitee I got stucked on the sell button. I couldn't continue from there. I tried two times same result
> 
> As far as I see, you don't have any chats selected. Could you maybe record a video of the whole interaction so I have more context about where the problem comes.

I use testing as Invitee in test mode, with both true. Invitee > MyChat > Login > Select Chats > Sell > Stuck.

**Review by lmangall — APPROVED** [review]
LGTM!

**Review by 552020 — APPROVED** [review]
LGTM

**Pull request merged**
